/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 models\Casual.gltf --output output\Casual.js --transform 
Files: models\Casual.gltf [3.13MB] > E:\Downloads\women\output\Casual-transformed.glb [755.9KB] (76%)
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/Quaternius/women/Casual-transformed.glb`

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF(link)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  useEffect(() => {

    console.log("Actions", actions)

    actions[`Idle`].play();

}, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
        </group>
        <group name="Casual_Body">
          <skinnedMesh name="Cube037" geometry={nodes.Cube037.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube037.skeleton} />
          <skinnedMesh name="Cube037_1" geometry={nodes.Cube037_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube037_1.skeleton} />
        </group>
        <group name="Casual_Feet">
          <skinnedMesh name="Cube070" geometry={nodes.Cube070.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube070.skeleton} />
          <skinnedMesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube070_1.skeleton} />
        </group>
        <group name="Casual_Head">
          <skinnedMesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube001.skeleton} />
          <skinnedMesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube001_1.skeleton} />
          <skinnedMesh name="Cube001_2" geometry={nodes.Cube001_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube001_2.skeleton} />
          <skinnedMesh name="Cube001_3" geometry={nodes.Cube001_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube001_3.skeleton} />
        </group>
        <skinnedMesh name="Casual_Legs" geometry={nodes.Casual_Legs.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Casual_Legs.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload(link)