/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ..\models\Building Red.glb --output output\Building Red.js --keepnames --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/J-Toastie/Models/Building Red.glb`;

export function ModelJToastieBuildingRed(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <group name="BuildingRed1" position={[-0.112, 1.665, 0.554]} rotation={[-Math.PI / 2, 0, 0]} scale={60}>
        <mesh name="BuildingRed1_1" castShadow receiveShadow geometry={nodes.BuildingRed1_1.geometry} material={materials.window_frame} />
        <mesh name="BuildingRed1_2" castShadow receiveShadow geometry={nodes.BuildingRed1_2.geometry} material={materials.brick_shade1} />
        <mesh name="BuildingRed1_3" castShadow receiveShadow geometry={nodes.BuildingRed1_3.geometry} material={materials.window_glass} />
        <mesh name="BuildingRed1_4" castShadow receiveShadow geometry={nodes.BuildingRed1_4.geometry} material={materials.sandstone} />
        <mesh name="BuildingRed1_5" castShadow receiveShadow geometry={nodes.BuildingRed1_5.geometry} material={materials.brick_shade2} />
        <mesh name="BuildingRed1_6" castShadow receiveShadow geometry={nodes.BuildingRed1_6.geometry} material={materials.concrete} />
        <mesh name="BuildingRed1_7" castShadow receiveShadow geometry={nodes.BuildingRed1_7.geometry} material={materials.wood} />
      </group>
    </group>
  )
}

useGLTF.preload(link)
