/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 models\fish-bones.glb --output output\fish-bones.js --transform 
Files: models\fish-bones.glb [34.07KB] > E:\Downloads\kenney_food-kit\JSX\output\fish-bones-transformed.glb [5.8KB] (83%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/KennyNL/Food/Models/fish-bones-transformed.glb`;

export function ModelKennyNLFoodFishBones(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['fish-bones_1'].geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload(link)
