/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 models\fries.glb --output output\fries.js --transform 
Files: models\fries.glb [59.23KB] > E:\Downloads\kenney_food-kit\JSX\output\fries-transformed.glb [7.52KB] (87%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/KennyNL/Food/Models/fries-transformed.glb`;

export function ModelKennyNLFoodFries(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.fries_1.geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload(link)
