/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/KennyNL/Graveyard/Models/lightpost-single.glb`;

export default function LightpostSingle(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['lightpost-single_1'].geometry}
        material={materials.colormap}
      />
    </group>
  )
}

useGLTF.preload(link)
