/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Security Camera.glb -T 
Files: Security Camera.glb [43.58KB] > F:\My Documents\Sites\games\plinko\public\models\Security Camera-transformed.glb [6.46KB] (85%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelSecurityCamera(props) {
  const { nodes, materials } = useGLTF('models/Security Camera-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['NurbsPath-Mesh'].geometry} material={materials.DarkGray} />
      <mesh geometry={nodes['NurbsPath-Mesh_1'].geometry} material={materials.Cream} />
      <mesh geometry={nodes['NurbsPath-Mesh_2'].geometry} material={materials.Black} />
      <mesh geometry={nodes['NurbsPath-Mesh_3'].geometry} material={materials.LightGray} />
    </group>
  )
}

useGLTF.preload('models/Security Camera-transformed.glb')
