/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ..\models\Wooden Fence.glb --output output\Wooden Fence.js --keepnames --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/J-Toastie/Models/Wooden Fence.glb`;

export function ModelJToastieWoodenFence(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <group name="WoodenFence" position={[0, 0.749, 0]} rotation={[-2.094, 1.571, 0]} scale={54}>
        <mesh name="WoodenFence_1" castShadow receiveShadow geometry={nodes.WoodenFence_1.geometry} material={materials.wood} />
        <mesh name="WoodenFence_2" castShadow receiveShadow geometry={nodes.WoodenFence_2.geometry} material={materials.wood_shaved} />
        <mesh name="WoodenFence_3" castShadow receiveShadow geometry={nodes.WoodenFence_3.geometry} material={materials.nail} />
      </group>
    </group>
  )
}

useGLTF.preload(link)
